### ISSUE TITLE
About the experiments on CIFAR-10

### ISSUE THREAD

**Issue by YonghaoXu** [weilinie/JARE#1]
Hi Weili, 

I have read your paper and found it an interesting work. Can you share the implementation for the quantitative evaluation on the CIFAR-10 dataset?

Thank you for your time!
Yonghao

**Comment by weilinie** [comment]
Hi @YonghaoXu, thanks for your interest in our work. I just added the implementation for experiments on CIFAR-10. Hope you find it useful!

**Comment by YonghaoXu** [comment]
Thank you for your sharing!
